export const DEMO_USER_ID = "demo-student";

export const defaultStudentSeed = {
  uid: "108428",
  password: "123456",
  role: "Student",
  name: "Ronit Soni",
  email: "ronitsoni@gmail.com",
  mobile: "9999999991",
  university: "SUxCG 712",
  attendance: {
    semester: "Semester 2",
    present: 126,
    total: 146,
    bonus: 2,
    percentLabel: 88,
    startDate: "29/01/2026",
    endDate: "30/06/2026",
  },
  subjects: [
    "SU11 - GIT & GITHUB",
    "SU12 - C Language",
    "SU13 - HTML/CSS/JS",
    "SU14 - UI/UX FIGMA",
    "SU15 - MATHS",
    "SU16 - JavaScript",
    "SU0201 - ReactJS",
    "SU0202 - NodeJS",
    "SU0203 - NoSQL",
    "SU0204 - OOPS",
    "SU0205 - Maths 2",
    "SU0206 - EVS",
    "SU0207 - IR 01",
    "SU0208 - IR 02",
  ],
  mentors: [{ name: "Ankita", batch: "SUxCG 712" }],
  assignments: 0,
  pendingAssignments: 0,
  events: [],
};

export const demoStudentSafeUser = {
  _id: DEMO_USER_ID,
  uid: defaultStudentSeed.uid,
  role: defaultStudentSeed.role,
  name: defaultStudentSeed.name,
  email: defaultStudentSeed.email,
  mobile: defaultStudentSeed.mobile,
  university: defaultStudentSeed.university,
  image: "",
  attendance: defaultStudentSeed.attendance,
  subjects: defaultStudentSeed.subjects,
  mentors: defaultStudentSeed.mentors,
  assignments: defaultStudentSeed.assignments,
  pendingAssignments: defaultStudentSeed.pendingAssignments,
  events: defaultStudentSeed.events,
};
